[package]
name = "sha256"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
sha2 = { version = "0.10" }
proptest = "1.6"
chacha20 = "0.9"
rand = "0.9"
# noir-runner = { git = "https://github.com/noir-lang/noir-runner", branch = "main" }
noir-runner = { path = "../runner" }
